# docker buildx build -f Dockerfile.reuse-origin-image --platform linux/amd64,linux/arm64 -t berejant/casdoor:latest --push .

FROM --platform=$BUILDPLATFORM golang:1.20.12 AS back
ARG BUILDPLATFORM
ARG TARGETPLATFORM
ARG TARGETOS
ARG TARGETARCH
WORKDIR /go/src/casdoor
# to use cache
COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod go mod download
COPY . .
RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build ./build.sh
RUN go test -v -run TestGetVersionInfo ./util/system_test.go ./util/system.go > version_info.txt

FROM --platform=$TARGETPLATFORM casbin/casdoor:latest
ARG USER=casdoor
ARG TARGETARCH
COPY --from=back --chown=$USER:$USER /go/src/casdoor/server_${BUILDX_ARCH} ./server
COPY --from=back --chown=$USER:$USER /go/src/casdoor/swagger ./swagger
COPY --from=back --chown=$USER:$USER /go/src/casdoor/conf/app.conf ./conf/app.conf
COPY --from=back --chown=$USER:$USER /go/src/casdoor/version_info.txt ./go/src/casdoor/version_info.txt

ENTRYPOINT ["/server"]
